services:
  web:
    container_name: bank-backend-web
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    container_name: bank-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm","run","dev","--","--host"]
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      npm_config_ignore_scripts: "false"
    volumes:
      - .:/app
      - /app/node_modules
